export const sakariNames = [
  "Sakari",
  "Sakke",
  "Sakkea",
  "Sakelle",
  "Sakarille",
  "Saken",
  "Sakarin"
];
export const sakariResponses = [
  "Pää kii aki!",
  "Turhaa mua syytät, salee topin vika.",
  "Hyvä vadee!",
  "Mä oon aina oikeessa!",
  "NO MITÄ???",
  "Mitä sä mua huutelet??",
  "Huoh....",
  "Hiljaa saatana!",
  "Eiku C-Line!",
  "joojooojooo",
  "En ymmärrä, voisitko esim. vetää käteen?",
  "PAIKALLA!",
  "WAT? Wiltzu sammu mua enne!",
  "Älä häiritte, ny o **** kädessä"
];
export const randomQuote = [
  "Paska puhetta...",
  "Antsaa hyssessä!",
  "Voimaa ja kulmaa \u{1F4AA}",
  "No en tosta kyllä tiiä, mut on ne prodigyn lätyt kyllä paskoja.",
  "No niinpä.",
  "Pakko muuten todeta, et on se Pauli vaa maailman paras frisbeegolffari!",
  "EIHÄN??",
  "HYVÄ VADEE!",
  "Tilanteesta oltais selvitty satasen roci heitolla...",
  "Aijaaok",
  "Tiiä sitte siitäkää",
  "\u{1F603}\u{1F603}\u{1F603}\u{1F603}\u{1F603}",
  "Ennenkaikkea joukkue!",
  "Ennenkaikkea layuppi!",
  "Nukuttii ja mentii eteenpäin!",
  "Nämä on ny näitä",
  "Oispa kaljaa...",
  "Eiku C-Line!!",
  "Sattuuhan näitä...",
  "EI HELVETIN KUUSTOISTA!",
  "Homohintti!",
  "Onko nyt noinkaan...",
  "Mutsis o",
  "No ei kyllä nyt kiinnosta vittuakaa",
  "Ai kaks rivinen aj-dessu???",
  "TOPII??? Mites se suihkukaappi?",
  "Tää on kyl nyt iha yhtä paskaa Hirsimäen putti SM-kisoissa 2018 vikalla väylällä...",
  "EZ4ENCE!!",
  "Oiskohan aika lähtee Saluunaan ryyppää?",
  "RÄTÄTÄTÄTÄTÄTÄTÄTÄTÄTÄÄTÄÄ"
];

export const randomGoodMorning = [
  "HYVÄÄ HUOMENTA SANKARIT!!! \n",
  "Ja paskaa päivän alotusta vaan kaikille Sankareille.. \n",
  "Ei vitun vittu, taas ois uus päivä, toivottavasti kaikki kuolee. \n",
  "AI ETTÄ KUINKA IHANA AAMU! LINNUT LAULAA \u{1F3B5} JA KAIKKI ON IHANASTI! \n",
  "Noniin, oltaisko tänään taas Sankareita kaikki? Semmonen fiilis mulla ainaki on! \n",
  "Mitäköhän veikkaatte? Kuinka moni sankareista on tänä aamuna talissa ja kuinka moni töissä?\n",
  "Oli se jallu hyvä idea eilen... Tänään ei taas siltä tunnu...\n",
  "JA EIKUN UUTEEN NOUSUUN!\n",
  "Huomenta vaan juu että tota noin. \n",
  "Oisko jo pelejäpelejäpelejäpelejäpelejäpelejäpelejä????\n",
  "JALLU! JALLU! JALLU!\n",
  "I MORGON ÄR DET FRIDAG! WWHUUUUUUYEYEYEYYEE!",
  "Joo, ei kyllä tänään pysty, takasin pullolle."
];

export const weatherEmojis = {
  Clouds: "\u{2601}",
  Clear: "\u{2600}",
  Rain: "\u{2614}",
  Snow: "\u{2744}",
  Drizzle: "\u{2614}"
};

export const giphySearchWords = [
  "morning",
  "discgolf",
  "party",
  "sad",
  "happy",
  "sunshine",
  "rain",
  "erotic",
  "beer",
  "booze",
  "alcohol",
  "funny",
  "lol",
  "vodka",
  "russian"
];

export const citys = [
  "Akaa",
  "Alajärvi",
  "Alavus",
  "Espoo",
  "Forssa",
  "Haapajärvi",
  "Haapavesi",
  "Hamina",
  "Hanko",
  "Harjavalta",
  "Heinola",
  "Helsinki",
  "Huittinen",
  "Hyvinkää",
  "Hämeenlinna",
  "Iisalmi",
  "Ikaalinen",
  "Imatra",
  "Joensuu",
  "Jyväskylä",
  "Jämsä",
  "Järvenpää",
  "Kaarina",
  "Kajaani",
  "Kalajoki",
  "Kangasala",
  "Kankaanpää",
  "Kannus",
  "Karkkila",
  "Kaskinen",
  "Kauhajoki",
  "Kauhava",
  "Kauniainen",
  "Kemi",
  "Kemijärvi",
  "Kerava",
  "Keuruu",
  "Kitee",
  "Kiuruvesi",
  "Kokemäki",
  "Kokkola",
  "Kotka",
  "Kouvola",
  "Kristiinankaupunki",
  "Kuhmo",
  "Kuopio",
  "Kurikka",
  "Kuusamo",
  "Lahti",
  "Laitila",
  "Lappeenranta",
  "Lapua",
  "Lieksa",
  "Lohja",
  "Loimaa",
  "Loviisa",
  "Maarianhamina",
  "Mikkeli",
  "Mänttä-Vilppula",
  "Naantali",
  "Nivala",
  "Nokia",
  "Nurmes",
  "Närpiö",
  "Orimattila",
  "Orivesi",
  "Oulainen",
  "Oulu",
  "Outokumpu",
  "Paimio",
  "Parainen",
  "Parkano",
  "Pieksämäki",
  "Pietarsaari",
  "Pori",
  "Porvoo",
  "Pudasjärvi",
  "Pyhäjärvi",
  "Raahe",
  "Raasepori",
  "Raisio",
  "Rauma",
  "Riihimäki",
  "Rovaniemi",
  "Saarijärvi",
  "Salo",
  "Sastamala",
  "Savonlinna",
  "Seinäjoki",
  "Somero",
  "Suonenjoki",
  "Tampere",
  "Tornio",
  "Turku",
  "Ulvila",
  "Uusikaarlepyy",
  "Uusikaupunki",
  "Vaasa",
  "Valkeakoski",
  "Vantaa"
];
